header finalizado
alvaroaxsmith/ecommerce-clientside pull request #13
Opened 2022-12-29 21:18 UTC by IsisFer

2022-12-29 21:37 UTC, IgorAntonio22 requested changes
Correções para serem realizadas: (Descritas no print abaixo)

Para que o link funcione, copie e cole na aba do navegador.

[https://iili.io/HTsuvKx.png](url)

2023-01-06 14:18 UTC, IgorAntonio22 requested changes
Ótimo, as correções foram feitas! Porém agora precisamos realizar a integração do código principal da branch Develop junto à sua branch feat:header.

2023-01-07 18:51 UTC, caio-magnani commented
Precisamos de fazer alguns ajustes no header:
1. Alinhamento dos componentes -> Reduzir ao máximo a falta de simetria na tela.
2. Tamanho do botão de Buscar e ícone -> O ícone do botão Buscar comunica ao usuário de "buscar por pessoas" e não por produtos recomendo ícone simples de Lupa.

Atualizei o Header no figma com os componentes de busca.

2023-01-12 20:24 UTC, caio-magnani approved these changes
LGFM

2023-01-12 20:29 UTC, IgorAntonio22 approved these changes

2023-01-12 20:35 UTC, merged